version: "3"
services:
  dbPostgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 31543:5432
    volumes:
      - /home/giova/repositories/tdd-database-2/data:/var/lib/postgresql/data